stages:
  - release

release:
  stage: release
  tags:
    - usody_worker
  only:
    - tags
  script:
    - poetry version $CI_COMMIT_TAG
    - git cliff -o CHANGELOG.md
    - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
    - poetry publish --build
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.whl
      - CHANGELOG.md
